apiVersion: apps/v1
kind: Deployment
metadata:
  name: social-net
spec:
  replicas: 1
  selector:
    matchLabels:
      app: social-net
  template:
    metadata:
      labels:
        app: social-net
    spec:
      containers:
        - name: social-net
          image: user0107/social-net-app:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: social-net-service
spec:
  type: LoadBalancer
  selector:
    app: social-net
  ports:
    - port: 80
      targetPort: 80

